# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: Apache-2.0

name: Linux App

on:
  push:
    branches:
      - master

jobs:
  AppImage:
    runs-on: ubuntu-latest
    container: ghcr.io/gitjournal/flutter-android-sdk:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: ./scripts/test.sh
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: Unit Tests ${{ matrix.os }} ${{ matrix.sdk }}
      #     path: test-results.xml
      #     reporter: jest-junit
      - name: Unlock Secrets
        env:
          GITCRYPT_KEY: ${{ secrets.GITCRYPT_KEY }}
        run: ./scripts/decrypt_secrets.sh
      - name: Setup Env
        run: dart ./scripts/setup_env.dart
      - run: flutter pub get
      - name: Build
        run: ./scripts/build_linux.sh
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: GitJournal-latest-x86_64.AppImage
          if-no-files-found: error
