package main

// DO NOT EDIT, this file is generated by hover at compile-time for the image_picker plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	image_picker "github.com/go-flutter-desktop/plugins/image_picker"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&image_picker.ImagePickerPlugin{}))
}
