package main

// DO NOT EDIT, this file is generated by hover at compile-time for the package_info plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	package_info "github.com/go-flutter-desktop/plugins/package_info"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&package_info.PackageInfoPlugin{}))
}
