package main

// DO NOT EDIT, this file is generated by hover at compile-time for the url_launcher plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	url_launcher "github.com/go-flutter-desktop/plugins/url_launcher"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&url_launcher.UrlLauncherPlugin{}))
}
