default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store"
    )
    #upload_to_app_store(skip_metadata: true, skip_screenshots: true)
    upload_to_testflight(apple_id:"1466519634", skip_waiting_for_build_processing:true)
  end
end
